"""add auth attempts and token version

Revision ID: 2d8932d93817
Revises: 3ce1ff2fae2a
Create Date: 2026-02-16 22:02:54.175449

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2d8932d93817'
down_revision: Union[str, Sequence[str], None] = '3ce1ff2fae2a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('auth_attempts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=320), nullable=False),
    sa.Column('action', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_auth_attempts_action'), 'auth_attempts', ['action'], unique=False)
    op.create_index(op.f('ix_auth_attempts_created_at'), 'auth_attempts', ['created_at'], unique=False)
    op.create_index(op.f('ix_auth_attempts_email'), 'auth_attempts', ['email'], unique=False)
    op.add_column("users", sa.Column("token_version", sa.Integer(), nullable=False, server_default="0"))
    op.alter_column("users", "token_version", server_default=None)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'token_version')
    op.drop_index(op.f('ix_auth_attempts_email'), table_name='auth_attempts')
    op.drop_index(op.f('ix_auth_attempts_created_at'), table_name='auth_attempts')
    op.drop_index(op.f('ix_auth_attempts_action'), table_name='auth_attempts')
    op.drop_table('auth_attempts')
    # ### end Alembic commands ###
