"""add login codes

Revision ID: 3ce1ff2fae2a
Revises: b645a246b67a
Create Date: 2026-02-16 01:16:24.759536

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3ce1ff2fae2a'
down_revision: Union[str, Sequence[str], None] = 'b645a246b67a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('login_codes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('code_hash', sa.String(length=128), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.Column('used_at', sa.DateTime(), nullable=True),
    sa.Column('attempts', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_login_codes_expires_at'), 'login_codes', ['expires_at'], unique=False)
    op.create_index(op.f('ix_login_codes_user_id'), 'login_codes', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_login_codes_user_id'), table_name='login_codes')
    op.drop_index(op.f('ix_login_codes_expires_at'), table_name='login_codes')
    op.drop_table('login_codes')
    # ### end Alembic commands ###
