"""add trust policy and trusted devices

Revision ID: 6d6b0de01e90
Revises: 2d8932d93817
Create Date: 2026-02-16 22:29:42.311444

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6d6b0de01e90'
down_revision: Union[str, Sequence[str], None] = '2d8932d93817'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('trusted_devices',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('token_hash', sa.String(length=128), nullable=False),
    sa.Column('policy', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=True),
    sa.Column('last_used_at', sa.DateTime(), nullable=True),
    sa.Column('revoked_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_trusted_devices_created_at'), 'trusted_devices', ['created_at'], unique=False)
    op.create_index(op.f('ix_trusted_devices_expires_at'), 'trusted_devices', ['expires_at'], unique=False)
    op.create_index(op.f('ix_trusted_devices_revoked_at'), 'trusted_devices', ['revoked_at'], unique=False)
    op.create_index(op.f('ix_trusted_devices_token_hash'), 'trusted_devices', ['token_hash'], unique=False)
    op.create_index(op.f('ix_trusted_devices_user_id'), 'trusted_devices', ['user_id'], unique=False)
    op.add_column(
        'users',
        sa.Column('trust_policy', sa.String(length=20), nullable=False, server_default='standard'),
    )
    op.add_column(
        'users',
        sa.Column('is_blocked', sa.Boolean(), nullable=False, server_default=sa.false()),
    )
    op.alter_column('users', 'trust_policy', server_default=None)
    op.alter_column('users', 'is_blocked', server_default=None)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'is_blocked')
    op.drop_column('users', 'trust_policy')
    op.drop_index(op.f('ix_trusted_devices_user_id'), table_name='trusted_devices')
    op.drop_index(op.f('ix_trusted_devices_token_hash'), table_name='trusted_devices')
    op.drop_index(op.f('ix_trusted_devices_revoked_at'), table_name='trusted_devices')
    op.drop_index(op.f('ix_trusted_devices_expires_at'), table_name='trusted_devices')
    op.drop_index(op.f('ix_trusted_devices_created_at'), table_name='trusted_devices')
    op.drop_table('trusted_devices')
    # ### end Alembic commands ###
